#  Wayland & Display Settings
linux_display_server wayland
wayland_titlebar_color system

# Distribute leftover vertical pixel space evenly instead of at the bottom
placement_strategy center

# Window Padding & Aesthetics
window_padding_width 0


# Disable Kitty's internal window decorations
hide_window_decorations yes

# Transparency & Opacity
background_opacity 0.85

# Font & Style
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size           11.0

disable_ligatures   never
modify_font cell_height 0px

# Tighten vertical line spacing
adjust_line_height 0

enable_audio_bell no
confirm_os_window_close 0

map enter send_text normal \r

