{
  lib,
  pkgs,
  config,
  osConfig ? null,
  ...
}:

let
  cfg = config.metronome.apps.hyprland;
  isDefault = (config.metronome.defaults.desktop-environment == "hyprland");
  displays =
    if osConfig != null && osConfig ? metronome.hardware.displays then
      osConfig.metronome.hardware.displays
    else
      { };

  generateMonitorLua =
    name: d:
    let
      outputName = d.output or name;
    in
    ''
      hl.monitor({
      	output = "${outputName}",
      	mode = "${d.mode}",
      	position = "${d.position}",
      	scale = ${toString d.scale},
      ${lib.optionalString (d ? transform && d.transform != null) "	transform = ${toString d.transform},\n"}${
        lib.optionalString (d ? vrr && d.vrr != null) "	vrr = ${toString d.vrr},\n"
      }${lib.optionalString (d ? bitdepth && d.bitdepth != null) "	bitdepth = ${toString d.bitdepth},\n"}${
        lib.optionalString (d ? cm && d.cm != null) "	cm = \"${d.cm}\",\n"
      }})
    '';

  workspaceList = lib.flatten (
    lib.mapAttrsToList (
      name: d:
      let
        outputName = d.output or name;
      in
      map (
        w:
        ''"${toString w}, monitor:${outputName}${
          if (d.primary or false) && w == (builtins.head d.workspaces) then ", default:true" else ""
        }"''
      ) (d.workspaces or [ ])
    ) displays
  );

  workspacesLua =
    if workspaceList != [ ] then
      ''
        hl.config({
        	workspace = {
        		${lib.concatStringsSep ",\n\t\t" workspaceList},
        	},
        })
      ''
    else
      "";

  generatedMonitorsLua =
    let
      monitorBlocks = lib.concatStringsSep "\n" (lib.mapAttrsToList generateMonitorLua displays);
    in
    if displays != { } then
      monitorBlocks + (lib.optionalString (workspacesLua != "") "\n" + workspacesLua)
    else
      "";
in
{
  options.metronome.apps.hyprland = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = isDefault;
      description = "enable hyprland desktop environment";
    };

    monitors = lib.mkOption {
      type = lib.types.nullOr (lib.types.either lib.types.path lib.types.lines);
      default = null;
      description = "Host-specific monitors configuration override (path to a .lua file or lua string)";
    };
  };

  config = lib.mkIf cfg.enable {

    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = false;
    };

    xdg.configFile = {
      "hypr/hyprland.lua".source = ./hyprland.lua;
      "hypr/defaults.lua".text = ''
        -- Auto-generated by Metronome NixOS module
        return {
          terminal = ${if config.metronome.defaults.terminal != null then ''"${config.metronome.defaults.terminal}"'' else "nil"},
          fileManager = ${if config.metronome.defaults.file-explorer != null then ''"${config.metronome.defaults.file-explorer}"'' else "nil"},
          webBrowser = ${if config.metronome.defaults.web-browser != null then ''"${config.metronome.defaults.web-browser}"'' else "nil"},
        }
      '';
    } // (lib.optionalAttrs (cfg.monitors != null || generatedMonitorsLua != "") {
      "hypr/monitors.lua" =
        if cfg.monitors != null then
          (if builtins.isPath cfg.monitors then { source = cfg.monitors; } else { text = cfg.monitors; })
        else
          { text = "-- Auto-generated by Metronome from hardware.displays\n" + generatedMonitorsLua; };
    });

    home.packages = with pkgs; [
      hyprcursor
      nordzy-cursor-theme
      hyprshot
      wl-clipboard
    ];
  };
}
