{
  lib,
  pkgs,
  config,
  ...
}:

let
  cfg = config.metronome.apps.hyprland;
  isDefault = (config.metronome.defaults.desktop-environment == "hyprland");
in
{
  options.metronome.apps.hyprland = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = isDefault;
      description = "enable hyprland desktop environment";
    };

    monitors = lib.mkOption {
      type = lib.types.nullOr (lib.types.either lib.types.path lib.types.lines);
      default = null;
      description = "Host-specific monitors configuration (path to a .lua file or lua string)";
    };
  };

  config = lib.mkIf cfg.enable {

    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = false;
    };

    xdg.configFile = {
      "hypr/hyprland.lua".source = ./hyprland.lua;
      "hypr/defaults.lua".text = ''
        -- Auto-generated by Metronome NixOS module
        return {
          terminal = ${if config.metronome.defaults.terminal != null then ''"${config.metronome.defaults.terminal}"'' else "nil"},
          fileManager = ${if config.metronome.defaults.file-explorer != null then ''"${config.metronome.defaults.file-explorer}"'' else "nil"},
          webBrowser = ${if config.metronome.defaults.web-browser != null then ''"${config.metronome.defaults.web-browser}"'' else "nil"},
        }
      '';
    } // (lib.optionalAttrs (cfg.monitors != null) {
      "hypr/monitors.lua" =
        if builtins.isPath cfg.monitors then { source = cfg.monitors; } else { text = cfg.monitors; };
    });

    home.packages = with pkgs; [
      hyprcursor
      nordzy-cursor-theme
      hyprshot
      wl-clipboard
    ];
  };
}
